### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by TGRHavoc** [Murgator/FiveM-vote-script#5]
Hey @Murgator 

Glad you like my script enough to claim it as your own! I dont have a problem with you modifying it and redistributing it, however you have to follow the original license.
This means you have to disclose the source of the code. This is normally done straight through github, by the "fork" feature. If you dont want to fork the project, then a simple link to the original repository in the readme, would be nice.

**Comment by Murgator** [comment]
Hello Havoc, in fact I tried to contact you several months ago because I had to make changes to the script. So I created a new link so that my visitors have an up-to-date script. I didn't know I had to mention it but I can obviously do it by the end of the week. Sorry again but I didn't know how to do it.

Have a good day !
David

**Comment by Murgator** [comment]
The modification has been made!

**Comment by Murgator** [comment]
Resolved
