### ISSUE TITLE
How do I find the Discord/Steam variable?

### ISSUE THREAD

**Issue by GHubbersz** [Murgator/FiveM-vote-script#8]
Config.identifier - Must be discordid or steamid. The player will be recognized on the server with this identifier

I tried to put my own discord ID in and I get an error when I type /checkvote. Says cant find my discord.

**Comment by GHubbersz** [comment]
I didnt mean to close this I still dont know the variable to assign.

**Comment by Murgator** [comment]
You must choose with which identifiers the players must be recognized on your server. With their STEAM or DISCORD.

If your players connect to your server with steam, set variable Config.identifier to "steamid" otherwise set to "discordid"

EDIT: From version 1.1.5 you must set Config.identifier to "steam" or "discord"

**Comment by Murgator** [comment]
README has been updated with a better explanation
